import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Wordmark, BirdMark, TbButton } from '@/components/ui';
import { useState } from 'react';
import { translations } from '@/lib/translations';
export const Navbar = ({ language, onLanguageChange }) => {
    const [mobileOpen, setMobileOpen] = useState(false);
    const t = translations[language];
    const isRTL = language === 'ar';
    return (_jsxs("nav", { className: "fixed top-0 left-0 right-0 bg-tb-sand border-b-4 border-tb-forest-ink shadow-[0_4px_0_0_rgba(28,46,37,1)] px-6 py-4 z-50", dir: isRTL ? 'rtl' : 'ltr', children: [_jsxs("div", { className: "flex justify-between items-center max-w-7xl mx-auto", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx(BirdMark, { className: "w-7 text-tb-forest-ink" }), _jsx(Wordmark, { variant: "dark", size: "md" })] }), _jsxs("div", { className: "hidden md:flex gap-8 items-center", children: [_jsx("a", { href: "#how", className: "font-syne text-sm font-bold text-tb-forest-ink/80 hover:text-tb-forest-ink hover:-translate-y-1 transition-transform uppercase tracking-wider", children: t.navbar.howItWorks }), _jsx("a", { href: "#features", className: "font-syne text-sm font-bold text-tb-forest-ink/80 hover:text-tb-forest-ink hover:-translate-y-1 transition-transform uppercase tracking-wider", children: t.navbar.features }), _jsx("a", { href: "#pricing", className: "font-syne text-sm font-bold text-tb-forest-ink/80 hover:text-tb-forest-ink hover:-translate-y-1 transition-transform uppercase tracking-wider", children: t.navbar.pricing }), _jsx("a", { href: "#login", className: "font-syne text-sm font-bold text-tb-forest-ink/80 hover:text-tb-forest-ink hover:-translate-y-1 transition-transform uppercase tracking-wider", children: t.navbar.login }), _jsx("button", { onClick: () => onLanguageChange(language === 'ar' ? 'en' : 'ar'), className: "bg-tb-ember hover:bg-tb-sienna text-tb-forest-ink font-syne font-bold text-xs tracking-widest px-3 py-1.5 border-2 border-tb-forest-ink shadow-neo hover:translate-x-[2px] transition-transform", children: language === 'ar' ? 'EN' : 'AR' })] }), _jsxs("div", { className: "flex items-center gap-4", children: [_jsx("div", { className: "hidden md:block", children: _jsx(TbButton, { variant: "primary", children: t.navbar.cta }) }), _jsx("button", { onClick: () => setMobileOpen(!mobileOpen), className: "md:hidden text-tb-forest-ink p-2 border-2 border-tb-forest-ink bg-white shadow-neo", children: "\u2630" })] })] }), mobileOpen && (_jsxs("div", { className: "md:hidden mt-4 flex flex-col gap-3 pb-4 border-t-2 border-tb-forest-ink pt-4", children: [_jsx("a", { href: "#how", className: "font-syne text-sm font-bold text-tb-forest-ink hover:text-tb-sienna py-2 uppercase tracking-wide", children: t.navbar.howItWorks }), _jsx("a", { href: "#features", className: "font-syne text-sm font-bold text-tb-forest-ink hover:text-tb-sienna py-2 uppercase tracking-wide", children: t.navbar.features }), _jsx("a", { href: "#pricing", className: "font-syne text-sm font-bold text-tb-forest-ink hover:text-tb-sienna py-2 uppercase tracking-wide", children: t.navbar.pricing }), _jsx("button", { onClick: () => {
                            onLanguageChange(language === 'ar' ? 'en' : 'ar');
                            setMobileOpen(false);
                        }, className: "font-syne text-sm font-black text-white bg-tb-forest-ink py-2 uppercase tracking-wide border-2 border-tb-forest-ink w-full text-center", children: language === 'ar' ? 'English' : 'العربية' }), _jsx(TbButton, { variant: "primary", className: "w-full mt-2", children: t.navbar.cta })] }))] }));
};
